import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/baslinereporting">BaslineReporting</Link>
        </li>
        <li>
          <Link to="/adhocreporting">AdhocReporting</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/demoaccount">DemoAccount</Link>
        </li>
        <li>
          <Link to="/emaillogin">Emaillogin</Link>
        </li>
        <li>
          <Link to="/filter">Filter</Link>
        </li>
        <li>
          <Link to="/friendlist">FriendList</Link>
        </li>
        <li>
          <Link to="/share">Share</Link>
        </li>
        <li>
          <Link to="/graphicalcharts">GraphicalCharts</Link>
        </li>
        <li>
          <Link to="/activityfeed">ActivityFeed</Link>
        </li>
        <li>
          <Link to="/inventorytrendanalysis">InventoryTrendAnalysis</Link>
        </li>
        <li>
          <Link to="/addfriends">AddFriends</Link>
        </li>
        <li>
          <Link to="/analytics">Analytics</Link>
        </li>
        <li>
          <Link to="/salesreporting">SalesReporting</Link>
        </li>
        <li>
          <Link to="/broadcastmessage">BroadcastMessage</Link>
        </li>
        <li>
          <Link to="/performancetracker">PerformanceTracker</Link>
        </li>
        <li>
          <Link to="/chatbackuprestore">ChatBackupRestore</Link>
        </li>
        <li>
          <Link to="/chatbot">Chatbot</Link>
        </li>
        <li>
          <Link to="/collagecreator">CollageCreator</Link>
        </li>
        <li>
          <Link to="/comments">Comments</Link>
        </li>
        <li>
          <Link to="/contactsharing">ContactSharing</Link>
        </li>
        <li>
          <Link to="/conversationthreading">ConversationThreading</Link>
        </li>
        <li>
          <Link to="/fanwall">FanWall</Link>
        </li>
        <li>
          <Link to="/followers">Followers</Link>
        </li>
        <li>
          <Link to="/gallery">Gallery</Link>
        </li>
        <li>
          <Link to="/gifs">GIFs</Link>
        </li>
        <li>
          <Link to="/groupchat">GroupChat</Link>
        </li>
        <li>
          <Link to="/groups">Groups</Link>
        </li>
        <li>
          <Link to="/hashtaggenerator">HashtagGenerator</Link>
        </li>
        <li>
          <Link to="/hashtags">Hashtags</Link>
        </li>
        <li>
          <Link to="/inappgifting">InAppGifting</Link>
        </li>
        <li>
          <Link to="/likepost">LikePost</Link>
        </li>
        <li>
          <Link to="/livefeedscheduling">LiveFeedScheduling</Link>
        </li>
        <li>
          <Link to="/mentionstagging">MentionsTagging</Link>
        </li>
        <li>
          <Link to="/muteunmutechat">MuteUnmuteChat</Link>
        </li>
        <li>
          <Link to="/nearbyfriends">NearbyFriends</Link>
        </li>
        <li>
          <Link to="/repost">Repost</Link>
        </li>
        <li>
          <Link to="/selfdestructivemessage">SelfDestructiveMessage</Link>
        </li>
        <li>
          <Link to="/sms">SMS</Link>
        </li>
        <li>
          <Link to="/smssettings">SMSSettings</Link>
        </li>
        <li>
          <Link to="/trending">Trending</Link>
        </li>
        <li>
          <Link to="/uploadmedia">Uploadmedia</Link>
        </li>
        <li>
          <Link to="/useraccount">UserAccount</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
